---
title: "LPA Ligation Efficiency"
author: "Kristina Kwock"
date: "3/8/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/LPA/Ligation Efficiency QC/Lot15")
```

```{r}
manual <- read.table('manualbuild15_adapter_ligation.tsv', header=T)
auto <- read.table('autobuild15_adapter_ligation.tsv', header=T)
```

```{r, warning=F, message=F}
library(dplyr)

# get the median for each partition

auto_results <- auto %>% group_by(partition)  %>% arrange(by_group=partition)%>% mutate(median_lig_efficiency = median(lig_efficiency), group="auto")

manual_results <- manual %>% group_by(partition)  %>% arrange(by_group=partition)%>% mutate(median_lig_efficiency = median(lig_efficiency), group="manual")

merged <- rbind(manual_results, auto_results)

merged
```

```{r, warning=F, message=F}
library(ggplot2)
library(ggpubr)

ggplot(merged, aes(x=partition, y=lig_efficiency, fill=group)) + 
  geom_boxplot() + 
  ggtitle('LPA: Automated vs. Manual build of LPA15') + 
  geom_hline(yintercept = 50, linetype='dashed', color='red') +
  stat_compare_means(method = "t.test") 
```


```{r, warning=F, message=F}
library(rstatix)
library(ggpubr)

stats_out <- merged %>% group_by(partition) %>% t_test(lig_efficiency~group) %>% add_significance()

stats_out
```

```{r}
merged %>% group_by(partition, group) %>% get_summary_stats(lig_efficiency, type = "mean_sd")
```

